config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]

      if cookies[:locale]
        if I18n.locale != cookies[:locale]
            I18n.locale = cookies[:locale]
        end
      end
    end

  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Moeda criada com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Moeda atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # layout 'adm'

  def index
    @name = params[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def application_name
        'Crypto Wallet'
    end

    def application_environment
        if Rails.env.development?
            'Desenvolvimento'
        elsif Rails.env.production?
            'Produção'
        else
            'Teste'
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="field col-lg-4  col-md-6 mt-3">
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control', placeholder: 'Bitcoin' %>
    </div>

    <div class="field col-lg-4  col-md-6 mt-3">
      <%= form.label :acronym, class: 'form-label' %>
      <%= form.text_field :acronym, class: 'form-control', placeholder: 'BTC'  %>
    </div>

    <div class="field col-lg-4  col-md-6 mt-3">
      <%= form.label :url_image, class: 'form-label' %>
      <%= form.text_field :url_image, class: 'form-control', placeholder: 'https://example.png'  %>
    </div>

    <div class="field col-lg-4 col-md-6 mt-3">
      <%= form.label :mining_type_id, class: 'form-label' %>
      <%= form.select('mining_type_id', @mining_type_options, { include_blank: 'Select' }, class: 'form-select' ) %>
    </div>

    <div class="actions mt-3 d-flex col-12">
      <%= form.submit "#{t("links.#{action_name}")} #{Coin.model_name.human}", class: 'btn btn-primary' %>
      <%= link_to t('links.back'), coins_path, class: 'btn btn-neutral mx-3' %>
    </div>
  </div>

<% end %>

app/views/coins/edit.html.erb
<h1><%= "#{Coin.model_name.human} - #{t('links.edit')}" %></h1>

<%= render 'form', coin: @coin %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Coin.model_name.human(count: Coin.count) %></h1>

<div class="table-responsive">
  <table class="table table-sm">
    <thead>
      <tr>
        <th><%= @coins.human_attribute_name(:description) %></th>
        <th><%= @coins.human_attribute_name(:acronym) %></th>
        <th><%= @coins.human_attribute_name(:url_image) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @coins.each do |coin| %>
        <tr>
          <td><%= coin.description %></td>
          <td><%= coin.acronym %></td>
          <td><%= image_tag coin.url_image, size: 25, alt: coin.description %></td>
          <td width="40px"><%= link_to t('links.show'), coin, class: "btn btn-primary btn-sm" %></td>
          <td width="40px"><%= link_to t('links.edit'), coin_path(coin), class: "btn btn-primary btn-sm" %></td>
          <td width="40px"><%= link_to t('links.delete'), coin, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: t('links.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="d-flex mt-2">
  <%= link_to "#{t('links.add')} #{Coin.model_name.human}", new_coin_path, class: 'btn btn-primary' %><br/>
  <%= link_to t('links.back'), '/', class: 'btn btn-neutral mx-3' %>
</div>

app/views/coins/new.html.erb
<h1><%= "#{t('links.new')} - #{Coin.model_name.human}" %></h1>

<%= render 'form', coin: @coin %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= Coin.human_attribute_name(:description) %></label>
    <input class="form-control" type="text" value="<%= @coin.description %>" disabled readonly>
  </div>  

  <div class="col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= Coin.human_attribute_name(:acronym) %></label>
    <input class="form-control" type="text" value="<%= @coin.acronym %>" disabled readonly>
  </div> 

  <div class="col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= Coin.human_attribute_name(:mining_type) %></label>
    <input class="form-control" type="text" value="<%= @coin.mining_type.description %>" disabled readonly>
  </div> 

  <div class="col-12 col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= Coin.human_attribute_name(:url_image) %>:</label>
    <input class="form-control mb-2" type="text" value="<%= @coin.url_image %>" disabled readonly>
    <%= image_tag @coin.url_image, size: 25, alt: @coin.description %>
  </div> 

  <div class="col-12">
    <div class="d-flex mt-3">
      <%= link_to "#{t("links.edit")} #{Coin.model_name.human}", edit_coin_path(@coin), class: 'btn btn-primary' %>
      <%= link_to t('links.back'), coins_path, class: 'btn btn-neutral mx-3' %>
    </div>
  </div>
</div>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-lg">
          <%= link_to "Crypto Wallet", welcome_index_path, class: 'navbar-brand' %>          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              
              <li class="nav-item position-relative">
                <%= link_to "#{Coin.model_name.human}", coins_path, class: [*('active' if params[:controller] == 'coins'),'nav-link'] %>
              </li>
              
              <li class="nav-item position-relative">
                <%= link_to "#{MiningType.model_name.human}", mining_types_path, class: [*('active' if params[:controller] == 'mining_types'),'nav-link'] %>
              </li>
            </ul>

              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= t('language') %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li>
                      <%= link_to 'Português - Brasil', '?locale=pt-BR', class: [*('disabled' if I18n.locale === 'pt-BR'), 'dropdown-item'] %>
                    </li>
                    <li>
                      <%= link_to 'English', '?locale=en', class: [*('disabled' if I18n.locale === 'en'), 'dropdown-item'] %>
                    </li>
                  </ul>
                </li>
              </ul>
          </div>
            
        </div>
      </nav>     

      <div class="container-lg pt-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="field col-lg-4  col-md-6 mt-3">
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control', placeholder: 'Proof of Work' %>
    </div>

    <div class="field col-lg-4  col-md-6 mt-3">
      <%= form.label :acronym, class: 'form-label' %>
      <%= form.text_field :acronym, class: 'form-control', placeholder: 'PoW'  %>
    </div>

    <div class="actions mt-3 d-flex col-12">
      <%= form.submit "#{t("links.#{action_name}")} #{MiningType.model_name.human}", class: 'btn btn-primary' %>
      <%= link_to t('links.back'), mining_types_path, class: 'btn btn-neutral mx-3' %>
    </div>

  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1><%= "#{MiningType.model_name.human} - #{t('links.edit')}" %></h1>

<%= render 'form', mining_type: @mining_type %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining types</h1>

<div class="table-responsive">
  <table class="table table-sm">
    <thead>
      <tr>
        <th><%= @mining_types.human_attribute_name(:description) %></th>
        <th><%= @mining_types.human_attribute_name(:acronym) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @mining_types.each do |mining_type| %>
        <tr>
          <td><%= mining_type.description %></td>
          <td><%= mining_type.acronym %></td>
          <td width="40px"><%= link_to t('links.show'), mining_type, class: "btn btn-primary btn-sm" %></td>
          <td width="40px"><%= link_to t('links.edit'), edit_mining_type_path(mining_type), class: "btn btn-primary btn-sm" %></td>
          <td width="40px"><%= link_to t('links.delete'), mining_type, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: t('links.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="d-flex mt-2">
  <%= link_to "#{t('links.add')} #{MiningType.model_name.human}", new_mining_type_path, class: 'btn btn-primary' %><br/>
  <%= link_to t('links.back'), '/', class: 'btn btn-neutral mx-3' %>
</div>

app/views/mining_types/new.html.erb
<h1><%= "#{t('links.new')} - #{MiningType.model_name.human}" %></h1>

<%= render 'form', mining_type: @mining_type %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= MiningType.human_attribute_name(:description) %></label>
    <input class="form-control" type="text" value="<%= @mining_type.description %>" disabled readonly>
  </div>  

  <div class="col-lg-4 col-md-6 mt-3">
    <label class="form-label"><%= MiningType.human_attribute_name(:acronym) %></label>
    <input class="form-control" type="text" value="<%= @mining_type.acronym %>" disabled readonly>
  </div> 

</div>

  <div class="col-12">
    <div class="d-flex mt-3">
      <%= link_to "#{t("links.edit")} #{MiningType.model_name.human}", edit_mining_type_path(@mining_type), class: 'btn btn-primary' %>
      <%= link_to t('links.back'), mining_types_path, class: 'btn btn-neutral mx-3' %>
    </div>
  </div>
</div>

app/views/welcome/_menu.html.erb
<h2>Cadastro</h2>
<ul>
    <li><%= link_to "Moedas", coins_path %></li>
    <li><%= link_to "Tipos de mineração", mining_types_path %></li>
</ul>

app/views/welcome/index.html.erb
<h1 class="display-3"><%= t('welcome') %> <%= application_name %>!  </h1>
<p class="lead">
  <%= t('greetings') %>
</p>



<!-- <%= render "menu" %> -->

<!-- <p>Você está no ambiente de <strong><%= application_environment %></strong></p> -->